{% set name = "metric-learn" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-learn-contrib/metric-learn/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 267e982a4fa09e706ab571937a8bde6ec67fe7c80daa1013cd0fa785d31f10e8

build:
  number: 0
  skip: True  # [py<36]
  # skipping py312 because of missing scikit-learn <1.3.2
  skip: True  # [py>311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - numpy >=1.11.0
    - python
    # <1.3.2 is due to API changes introduced after metric-learn 0.7.0 release
    # which cause a large amount of test failures
    - scikit-learn >=0.21.3,<1.3.2
    - scipy >=0.17.0
  run_constrained:
    # address segfault on osx-64
    - blas=*=openblas  # [osx and x86_64]

test:
  source_files:
    - test
    - pytest.ini
  requires:
    - pip
    - pytest
    - matplotlib-base
  commands:
    - pip check
    - pytest test
  imports:
    - metric_learn

about:
  home: https://github.com/scikit-learn-contrib/metric-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python implementations of metric learning algorithms
  description: metric-learn contains efficient Python implementations of several popular supervised and weakly-supervised metric learning algorithms. As part of scikit-learn-contrib, the API of metric-learn is compatible with scikit-learn, the leading library for machine learning in Python. This allows to use all the scikit-learn
    routines (for pipelining, model selection, etc) with metric learning algorithms through a unified interface.
  doc_url: https://contrib.scikit-learn.org/metric-learn/
  dev_url: https://github.com/scikit-learn-contrib/metric-learn

extra:
  recipe-maintainers:
    - bellet
    - perimosocordiae
    - terrytangyuan
    - wdevazelhes
