{% set name = "metric-learn" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b35246a1098d74163b16cc7779e0abfcbf9036050f4caa258e4fee55eb299cc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.11.0
    - python >={{ python_min }}
    - scikit-learn >=0.21.3
    - scipy >=0.17.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - metric_learn

about:
  home: http://github.com/scikit-learn-contrib/metric-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python implementations of metric learning algorithms

  description: metric-learn contains efficient Python implementations of several popular supervised and weakly-supervised metric learning algorithms. As part of scikit-learn-contrib, the API of metric-learn is compatible with scikit-learn, the leading library for machine learning in Python. This allows to use all the scikit-learn
    routines (for pipelining, model selection, etc) with metric learning algorithms through a unified interface.
  doc_url: http://contrib.scikit-learn.org/metric-learn/
  dev_url: http://github.com/scikit-learn-contrib/metric-learn

extra:
  recipe-maintainers:
    - bellet
    - perimosocordiae
    - terrytangyuan
    - wdevazelhes
